-- Homes and shop products now live in the database. Each row keeps the few
-- columns we search, sort and price by, plus a "data" column (JSON) holding the
-- rest of the details (photos, features, specs, options and so on).
--  source 'seed'  : the starter catalog loaded from server/seed/*.json at start-up
--  source 'owner' : created by an owner or vendor (the next part of the build)
-- Ids below 1000 are the starter items; new rows count up from 1000.
create table properties (
  id integer generated by default as identity (start with 1000) primary key,
  source text not null default 'seed' check (source in ('seed', 'owner')),
  owner_id uuid references users (id) on delete set null,
  review_status text not null default 'approved' check (review_status in ('pending', 'approved', 'rejected', 'paused')),
  listing_type text not null check (listing_type in ('rent', 'buy')),
  property_type text not null,
  city text not null,
  price numeric(12, 2) not null check (price >= 0),
  featured boolean not null default false,
  data jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index properties_browse_idx on properties (listing_type, review_status);

create table products (
  id integer generated by default as identity (start with 1000) primary key,
  source text not null default 'seed' check (source in ('seed', 'owner')),
  vendor_id uuid references users (id) on delete set null,
  published boolean not null default true,
  category text not null,
  name text not null,
  price numeric(12, 2) not null check (price >= 0),
  stock integer not null default 0 check (stock >= 0),
  data jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index products_browse_idx on products (published, category);
